name: Run generate-md-docs

on:
  workflow_dispatch:
    inputs:
      doc_type:
        description: Which docs to generate
        required: true
        default: vpr
        type: choice
        options:
          - vpr
          - lsr
      stack_version:
        description: Elastic Stack version (for example, `9.0.4`)
        type: string

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      # Set up
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Checkout elastic/built-docs
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: elastic/built-docs
          sparse-checkout: |
            raw/en/logstash/current
            raw/en/logstash-versioned-plugins/current
          sparse-checkout-cone-mode: true
          path: 'temp/built-docs'
      - name: Checkout elastic/logstash-docs
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: elastic/logstash-docs
          sparse-checkout: |
            docs/plugins
          sparse-checkout-cone-mode: true
          path: 'temp/logstash-docs'

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6

      - name: Generate files
        run: |
          npm ci
          node $GITHUB_WORKSPACE/src/index.js ${{ inputs.doc_type }} ${{ inputs.stack_version || '' }}

      - name: Open PR
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8
        with:
          commit-message: |
            update ${{ inputs.doc_type == 'lsr' && 'lsr and vpr' || 'vpr' }} docs
          branch: ${{ inputs.doc_type }}-update
          branch-suffix: timestamp
          title: |
            ${{ inputs.doc_type == 'lsr' && format('[{0}] ', inputs.stack_version) || ''}}Update ${{ inputs.doc_type == 'lsr' && 'LSR and VPR' || 'VPR' }} docs
          body: |
            Updates the ${{ inputs.doc_type == 'lsr' && 'LSR and VPR' || 'VPR' }} docs with the latest from elastic/logstash-docs.
          add-paths: docs/
