name: Run generate-md-docs

on:
  workflow_dispatch:
    inputs:
      doc_type:
        description: Which docs to generate
        required: true
        default: vpr
        type: choice
        options:
          - vpr
          - lsr
      stack_version:
        description: The Elastic Stack minor version (for example, `9.1`)
        type: string
  pull_request:

env:
  LSR_ID: logstash
  LSR_BRANCH: main
  VPR_ID: logstash-docs
  VPR_BRANCH: versioned_plugin_docs
  TEST_DOC_TYPE: lsr
  TEST_STACK_VERSION: '9.0'

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      lsr_updates: ${{ steps.lsr_updates.outputs.result }}
      vpr_updates: ${{ steps.vpr_updates.outputs.result }}
    steps:
      # Get current time, subtract 8 hours, convert to ISO 8601
      - name: Get timestamp for 8 hours ago
        id: timestamp
        run: |
          TIMESTAMP="$(date +'%Y-%m-%dT')$(($(date +%H) - 8))$(date +':%M:%S')"
          echo $TIMESTAMP

      # Check if there were any commits in the last 8 hours
      - name: Check for lsr updates
        id: lsr_updates
        uses: actions/github-script@v6
        env:
          TIMESTAMP: ${{ steps.timestamp.outputs.TIMESTAMP }}
        with:
          script: |
            const commits = await github.rest.repos.listCommits({
              owner: 'elastic',
              repo: process.env.LSR_ID,
              sha: process.env.LSR_BRANCH,
              since: '2025-06-10T9:52:00'
            })
            return commits.data.length > 0

      # Check if there were any commits in the last 8 hours
      - name: Check for vpr updates
        id: vpr_updates
        uses: actions/github-script@v6
        env:
          TIMESTAMP: ${{ steps.timestamp.outputs.TIMESTAMP }}
        with:
          script: |
            const commits = await github.rest.repos.listCommits({
              owner: 'elastic',
              repo: process.env.VPR_ID,
              sha: process.env.VPR_BRANCH,
              since: '2025-06-10T9:52:00'
            })
            return commits.data.length > 0

  generate-docs:
    runs-on: ubuntu-latest
    needs: check-for-updates
    if: ${{ needs.check-for-updates.outputs.lsr_updates || needs.check-for-updates.outputs.vpr_updates }}
    steps:
      # Set up
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout elastic/built-docs
        uses: actions/checkout@v4
        with:
          repository: elastic/built-docs
          sparse-checkout: |
            raw/en/logstash/current
            raw/en/logstash-versioned-plugins/current
          sparse-checkout-cone-mode: true
          path: 'temp/built-docs'
      - name: Checkout elastic/logstash-docs
        uses: actions/checkout@v4
        with:
          repository: elastic/logstash-docs
          sparse-checkout: |
            docs/plugins
          sparse-checkout-cone-mode: true
          path: 'temp/logstash-docs'

      - name: Get gemfile
        id: get_gemfile
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const gemfilename = 'Gemfile.jruby-3.1.lock.release'
            const gemfile = await github.rest.repos.getContent({
              owner: 'elastic',
              repo: 'logstash',
              path: gemfilename,
              ref: process.env.TEST_STACK_VERSION,
              headers: {
                accept: "application/vnd.github.raw+json",
              },
            });
            fs.mkdirSync(
              `${process.env.GITHUB_WORKSPACE}/temp/logstash/${process.env.TEST_STACK_VERSION}/`,
              { recursive: true }
            )
            fs.writeFileSync(
              `${process.env.GITHUB_WORKSPACE}/temp/logstash/${process.env.TEST_STACK_VERSION}/${gemfilename}`,
              gemfile.data
            )

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Generate files
        run: |
          npm ci
          node $GITHUB_WORKSPACE/src/index.js $TEST_DOC_TYPE $TEST_STACK_VERSION

      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     commit-message: update lsr and vpr docs
      #     branch: lsr-update
      #     branch-suffix: timestamp
      #     title: '[TEST] Update LSR docs'
      #     body: "This is just a test!!"
      #     add-paths: docs/
      #     base: ${{ github.head_ref }}
